apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: APIServer
  metadata:
    annotations:
      include.release.openshift.io/ibm-cloud-managed: "true"
      include.release.openshift.io/self-managed-high-availability: "true"
      include.release.openshift.io/single-node-developer: "true"
      oauth-apiserver.openshift.io/secure-token-storage: "true"
      release.openshift.io/create-only: "true"
    name: cluster
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: cbbc5804-42a4-4d8a-909b-6c5ad49cd245
    uid: 1015f39c-b936-4c3c-b5a6-75175af08a08
  spec:
    encryption:
      type: aescbc 
    audit:
      profile: Default
kind: List
metadata:
  resourceVersion: ""
